<a href="https://colab.research.google.com/github/noswolf/DSA_BIT/blob/master/Week2/DSA_Week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import required libraries

In [ ]:
import numpy as np

# 1-Dimensional Array

In [ ]:
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[1])               # Prints "2"
print(a)                  # Prints "[1 2 3]"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5 2 3]"

<class 'numpy.ndarray'>
(3,)
2
[1 2 3]
[5 2 3]


# Multi-Dimensional Array

## 2-D Arrays

In [ ]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(type(b))
print(b.shape)                     # Prints "(2, 3)" indicating 2 dimensions, 2 ranks and size/length of 3 for each rank
print(b)
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(2, 3)
[[1 2 3]
 [4 5 6]]
1 2 4


In [ ]:
c = np.array([['h','e','l','l','o'],['w','o','r','l','d']]) # Create a rank 2 array
print(c)
print(type(c))
print(c.shape)                      # Prints "(2, 5)"
print(c[1, 0], c[1, 2])             # Prints "w r"

[['h' 'e' 'l' 'l' 'o']
 ['w' 'o' 'r' 'l' 'd']]
<class 'numpy.ndarray'>
(2, 5)
w r


In [ ]:
d = np.array([['h','e','l','l','o'],['w','o','r','l','d'],['w','a','t','c','h']])
print(d.shape)                    # Prints "(3, 5)" indicating 2 dimensions, 3 ranks and size/length of 5 for each rank

(3, 5)


## 3-D Arrays

In [ ]:
e = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print(e)
print(e.shape)                    # Prints "(3, 2, 3)" indicating 3 dimensions, 2 ranks and size/length of 3 for each rank
print(e[0][0][0])                 # Prints "1"
print(e[0][1][2])                 # Prints "6" -> Dimension#0, Rank#1, index#2

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
(3, 2, 3)
1
6


#Sequential Search

In [1]:
def linear_search(data,target): 
    for i in range(len(data)): 
        if data[i] == target: 
            print('Found target at index: {}'.format(i))
            return True
    return False

In [2]:
data = [10,20,40,50]
linear_search(data,40)

Found target at index: 2


True

In [3]:
linear_search(data,100)

False