# Lab 3: Arrays

Lecturer: <code>Sirasit Lochanachit</code>

Course: 

<code>01526121 Data Structures and Algorithms [SIIE]
</code>

Term: <code>02/2025</code>

---

# Required Libraries

In [ ]:
import numpy as np
import timeit
import matplotlib.pyplot as plt

---

# Lab 3-1 Inserting at Different Positions of a List

## 1.1 Problem Description

Given an empty list `data = []`, record the **average** running time of insert(k, 20) in seconds with three different inserting patterns for each of the `N` calls:

*   Repeatedly insert at the beginning of a list
*   Repeatedly insert near the middle of a list
*   Repeatedly insert at the end of the list

**This could run very long, so brace yourself** and make sure to limit `number` argument in `timeit()` to `1,000` times (default is 1,000,000 times)

### Note ###
<code> timeit.Timer.timeit(number=1000000): </code>

Time number executions of the main statement. This executes the setup statement once, and then returns **the time it takes to execute the main statement a number of times**, measured in seconds as a float.

Please note that the default value of <code>number</code> argument is 1 million times throught the loop.

### Example ###
The code belows setup an empty list in `data` variable for each of the `n` calls to monitor how input size can grows from 1 to `number * n`.


In [ ]:
def stmt(data,n):
    for i in range(n):
        data.append(0)
    print(data)

In [ ]:
# Example 1

[timeit.timeit(f"""stmt(data, {n})""",
               setup = 'data = []; print("Resetting data")', 
               number=5, 
               globals=globals())
 for n in [1,2]]

- For the first `n`, it will execute 1 * 5 times then record the total running time.
- After this, it will reset  `data` variable into an empty list as described in `setup` option
- The second `n` will produce 10 data (as a result of running 2 * 5 times) and then record the total running time.

The resulted list shows the total running time for first `n` followed by the second `n`.

Let's look at another example

In [ ]:
# Example 2

[timeit.timeit(f"""data.append(0); print(data)""",
               setup = 'data = []; print("Resetting data")', 
               number=5, 
               globals=globals())
 for n in [1,2]]

This code will execute 5 times no matter what the value of `n` is.

Since an input size remains the same, it will result in similar running time. 

In [ ]:
ns = ['your code here']

In [ ]:
# Beginning of a list
data = []
[timeit.timeit('your code here') 'your code here']

In [ ]:
# Middle of a list
data = []
[timeit.timeit('your code here') 'your code here']

In [ ]:
# End of the list
data = []
[timeit.timeit('your code here') 'your code here']

### Edit table and fill your answer here

| Patterns / N    | 10 | 20 | 50 | 100 | 200 | 1000 |
| ----------- | ----------- | ----------- | ----------- | ----------- | ----------- | ----------- |
|  Beginning of a list    |   -    | -|- | -| - | - |
| Middle of a list  |   -     |  -|- | -| - | - |
| End of a list | - |  -|- | -| - | - |

### 1.2 What do you learn from this result? Discuss amongst your friends and write an answer below.

[Write your answer here]

---

# Lab 3-2 Append in a Dynamic Array

## 2.1 Problem Description

Given an incomplete implementation of a Dynamic Array using NumPy library

This array will have a fixed initial size of 1, but as elements are added to the list it may become necessary to create a new, larger backing array and copy our elements over. Each time we create a new backing array, we will **double** the capacity of the original.

Your task is to implement the `append()` method
* It should check first whether the current array is full of elements
  * If yes, then create a new array with a double capacity
    * Use np.empty(x, dtpe=object) to create a new array where x is equals to length of an array
    * Copy elements from old array to new array
    * Reassign `self.data` to a new array
  * Append the value
  * Increase the size counter by 1

In [ ]:
import numpy as np

class ArrayList:
    def __init__(self):
        self.data = np.empty(1, dtype=object)
        self.size = 0


    def append(self, value):
        ##################
        # Your code here
        ##################

    def __getitem__(self, idx):
        """Implements `x = self[idx]`"""
        assert isinstance(idx, int), 'Index must be an integer'
        if idx < 0:
            idx += self.size
        if idx < 0 or idx >= self.size:
            raise IndexError('list index out of range')
        return self.data[idx]


    def __setitem__(self, idx, value):
        """Implements `self[idx] = x`"""
        assert isinstance(idx, int), 'Index must be an integer'
        if idx < 0:
            idx += self.size
        if idx < 0 or idx >= self.size:
            raise IndexError('list index out of range')
        self.data[idx] = value


    def __delitem__(self, idx):
        """Implements `del self[idx]`"""
        assert isinstance(idx, int), 'Index must be an integer'
        if idx < 0:
            idx += self.size
        if idx < 0 or idx >= self.size:
            raise IndexError('list index out of range')
        for i in range(idx, self.size-1):
            self.data[i] = self.data[i+1]
        self.size -= 1


    def __len__(self):
        """Implements `len(self)`"""
        return self.size


    def __repr__(self):
        """Supports inspection"""
        return '[' + ','.join(repr(self.data[i]) for i in range(self.size)) + ']'

### 2.2 Test your code by executing the following commands:

In [ ]:
l1 = ArrayList()
for x in range(10):
    l1.append(x)
    print(l1.data)


[0]
[0 1]
[0 1 2 None]
[0 1 2 3]
[0 1 2 3 4 None None None]
[0 1 2 3 4 5 None None]
[0 1 2 3 4 5 6 None]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 None None None None None None None]
[0 1 2 3 4 5 6 7 8 9 None None None None None None]


---

# Lab 3-3 Amortized Time on Enlarging Dynamic Array Size

## 3.1 Problem Description

Your task is to update the append() method so that it can allocate memory by either a double or fixed size.

Re-write append() method so that it accepts one more argument `doubling` which can only accept True or False

If `doubling` is True, incrase an array size by double

If `doubling` is False, increse an array size by 1000


In [ ]:
import numpy as np

class ArrayList:
    def __init__(self):
        self.data = np.empty(1, dtype=object)
        self.size = 0


    def append(self, value, doubling=True):
        ##################
        # Your code here
        ##################

       def __getitem__(self, idx):
        """Implements `x = self[idx]`"""
        assert isinstance(idx, int), 'Index must be an integer'
        if idx < 0:
            idx += self.size
        if idx < 0 or idx >= self.size:
            raise IndexError('list index out of range')
        return self.data[idx]


    def __setitem__(self, idx, value):
        """Implements `self[idx] = x`"""
        assert isinstance(idx, int), 'Index must be an integer'
        if idx < 0:
            idx += self.size
        if idx < 0 or idx >= self.size:
            raise IndexError('list index out of range')
        self.data[idx] = value


    def __delitem__(self, idx):
        """Implements `del self[idx]`"""
        assert isinstance(idx, int), 'Index must be an integer'
        if idx < 0:
            idx += self.size
        if idx < 0 or idx >= self.size:
            raise IndexError('list index out of range')
        for i in range(idx, self.size-1):
            self.data[i] = self.data[i+1]
        self.size -= 1


    def __len__(self):
        """Implements `len(self)`"""
        return self.size


    def __repr__(self):
        """Supports inspection"""
        return '[' + ','.join(repr(self.data[i]) for i in range(self.size)) + ']'

Test your code by executing the following commands and you should get the same example results as shown here:

In [ ]:
l1 = ArrayList()
for x in range(10):
    l1.append(x, doubling=True)
    print(l1.data)

[0]
[0 1]
[0 1 2 None]
[0 1 2 3]
[0 1 2 3 4 None None None]
[0 1 2 3 4 5 None None]
[0 1 2 3 4 5 6 None]
[0 1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7 8 None None None None None None None]
[0 1 2 3 4 5 6 7 8 9 None None None None None None]


In [ ]:
l2 = ArrayList()
for x in range(10):
    l2.append(x, doubling=False)
    print(l2.data)


[0]
[0 1 None ... None None None]
[0 1 2 ... None None None]
[0 1 2 ... None None None]
[0 1 2 ... None None None]
[0 1 2 ... None None None]
[0 1 2 ... None None None]
[0 1 2 ... None None None]
[0 1 2 ... None None None]
[0 1 2 ... None None None]


## 3.2 Comparing Runtime

Given input size (n) that grows from 10 to 10,000

In [ ]:
ns = np.linspace(10, 10000, 50, dtype=int)

### 3.2.1 What is the runtime behaviour of **append** method with a double capacity when an array is full? Plot the graph to answer this.
* Each test of `n` should execute `10` rounds
* Uses methods from ArrayList class only

In [ ]:
ts1 = []
for n in ns:
    lst = ArrayList()
    s1 = timeit.timeit('Insert your code here')
    ts1.append(s1)

### 3.2.2 What is the runtime behaviour of **append** method with a fixed increase capacity of 1000 when an array is full? Plot the graph to answer this.
* Each test of `n` should execute `10` rounds
* Uses methods from ArrayList class only

In [ ]:
ts2 = []
for n in ns:
    lst = ArrayList()
    s2 = timeit.timeit('Insert your code here')
    ts2.append(s2)

### 3.2.3 Combine both plot to compare running time

*   Your plot should include x and y label and a title and a legend



In [ ]:
##################
# Your code here
##################

### 3.2.4 Why growing a new array by a constant amount has a slower runtime than by a double capacity? Discuss amongst your friends and write your answer below.

[Write your answer here]

---